M48
; DRILL file {KiCad (6.99.0-2225-g61f71e0814)} date Tue Aug  9 19:58:37 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-09T19:58:37+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-2225-g61f71e0814)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X27.475Y-142.55
X27.475Y-146.95
T0
M30
